# Site settings
title: RedBand Films
email: adam@redbandmovies.com
description: > # this means to ignore newlines until "baseurl:"
  RedBand
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jcroutworts94.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: jcroutworts94

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
